config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dnd, only: [] do
    collection do
      get :kouzla
      get :predmety
    end
  end

  resources :fate, only: [] do
    collection do
      get :triky
    end
  end

  resources :drd2, only: [] do
    collection do
      get :schopnosti
    end
  end
end

app/models/dnd.rb
module Dnd
  def self.table_name_prefix
    'dnd_'
  end
end

app/models/dnd/class_spell.rb
# == Schema Information
#
# Table name: class_spells
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  dnd_class_id :bigint           not null
#  spell_id     :bigint           not null
#
# Indexes
#
#  index_class_spells_on_dnd_class_id  (dnd_class_id)
#  index_class_spells_on_spell_id      (spell_id)
#
# Foreign Keys
#
#  fk_rails_...  (dnd_class_id => dnd_classes.id)
#  fk_rails_...  (spell_id => spells.id)
#
module Dnd
  class ClassSpell < ApplicationRecord
    belongs_to :spell
    belongs_to :dnd_class
  end
end

app/models/dnd/dnd_class.rb
# == Schema Information
#
# Table name: dnd_classes
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Dnd
  class DndClass < ApplicationRecord
    has_many :class_spells
    has_many :spells, through: :class_spells

    validates :name, presence: true, uniqueness: true
  end
end

app/models/dnd/item.rb
# == Schema Information
#
# Table name: dnd_items
#
#  id              :bigint           not null, primary key
#  attunement      :string           default([]), is an Array
#  bonus           :string           default([]), is an Array
#  combat_effect   :string           default([]), is an Array
#  description     :text
#  duration        :string
#  filter_duration :integer
#  filter_rarity   :integer          default([]), is an Array
#  interaction     :string
#  item            :string           default([]), is an Array
#  limit           :string           default([]), is an Array
#  original        :string
#  purpose         :string           default([]), is an Array
#  rarity          :string
#  rulebook        :string           default([]), is an Array
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
module Dnd
  class Item < ApplicationRecord
    scope :sort_by_czech_title_asc, -> { sort { |a, b| Dnd::Item.collator.compare(a.title, b.title) } }
    scope :sort_by_czech_title_desc, -> { sort { |a, b| Dnd::Item.collator.compare(b.title, a.title) } }
    scope :sort_by_item_and_title_asc, lambda {
      sort do |a, b|
        [Dnd::Item.collator.get_sort_key(a.item.first), Dnd::Item.collator.get_sort_key(a.title)] <=>
          [Dnd::Item.collator.get_sort_key(b.item.first), Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_item_and_title_desc, lambda {
      sort do |a, b|
        [Dnd::Item.collator.get_sort_key(b.item.first), Dnd::Item.collator.get_sort_key(a.title)] <=>
          [Dnd::Item.collator.get_sort_key(a.item.first), Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_rarity_and_title_asc, lambda {
      sort do |a, b|
        [a.filter_rarity.first, Dnd::Item.collator.get_sort_key(a.title)] <=>
          [b.filter_rarity.first, Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_rarity_and_title_desc, lambda {
      sort do |a, b|
        [b.filter_rarity.first, Dnd::Item.collator.get_sort_key(a.title)] <=>
          [a.filter_rarity.first, Dnd::Item.collator.get_sort_key(b.title)]
      end
    }

    DURATION = {
      'Ihned' => 0,
      '1 kolo' => 1,
      'X kol' => 2,
      '1 minuta' => 3,
      '5 minut' => 4,
      '10 minut' => 5,
      'X minut' => 6,
      '1 hodina' => 7,
      '2 hodiny' => 8,
      '4 hodiny' => 9,
      '6 hodin' => 10,
      '8 hodin' => 11,
      'X hodin' => 12,
      'X dní' => 13,
      'Do rozptýlení' => 14,
      'Permanentní' => 15,
      'Zvláštní' => 16,
      'nepovinný' => 17
    }.freeze

    RARITY = {
      'Běžný' => 0,
      'Neobvyklý' => 1,
      'Vzácný' => 2,
      'Velmi vzácný' => 3,
      'Legendární' => 4,
      'Artefakt' => 5
    }.freeze
  end
end

app/models/dnd/rulebook.rb
# == Schema Information
#
# Table name: rulebooks
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Dnd
  class Rulebook < ApplicationRecord
    has_many :sources
    has_many :spells, through: :sources
  end
end

app/models/dnd/source.rb
# == Schema Information
#
# Table name: sources
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  rulebook_id :bigint           not null
#  spell_id    :bigint           not null
#
# Indexes
#
#  index_sources_on_rulebook_id  (rulebook_id)
#  index_sources_on_spell_id     (spell_id)
#
# Foreign Keys
#
#  fk_rails_...  (rulebook_id => rulebooks.id)
#  fk_rails_...  (spell_id => spells.id)
#
module Dnd
  class Source < ApplicationRecord
    belongs_to :spell
    belongs_to :rulebook
  end
end

app/models/spell.rb
# == Schema Information
#
# Table name: spells
#
#  id                  :bigint           not null, primary key
#  casting             :integer
#  classes             :string           default([]), is an Array
#  components          :string
#  concentration       :boolean
#  description         :string
#  duration            :integer
#  level               :integer
#  original            :string
#  original_casting    :string
#  original_components :string
#  original_duration   :string
#  original_range      :string
#  range               :integer
#  ritual              :boolean
#  rulebook            :string           default([]), is an Array
#  school              :string
#  title               :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Spell < ApplicationRecord
  scope :sort_by_czech_title_asc, -> { sort { |a, b| Spell.collator.compare(a.title, b.title) } }
  scope :sort_by_czech_title_desc, -> { sort { |a, b| Spell.collator.compare(b.title, a.title) } }
  scope :sort_by_school_and_title_asc, lambda {
    sort do |a, b|
      [Spell.collator.get_sort_key(a.school), Spell.collator.get_sort_key(a.title)] <=>
        [Spell.collator.get_sort_key(b.school), Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_school_and_title_desc, lambda {
    sort do |a, b|
      [Spell.collator.get_sort_key(b.school), Spell.collator.get_sort_key(a.title)] <=>
        [Spell.collator.get_sort_key(a.school), Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_level_and_title_asc, lambda {
    sort do |a, b|
      [a.level, Spell.collator.get_sort_key(a.title)] <=> [b.level, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_level_and_title_desc, lambda {
    sort do |a, b|
      [b.level, Spell.collator.get_sort_key(a.title)] <=> [a.level, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_casting_and_title_asc, lambda {
    sort do |a, b|
      [a.casting, Spell.collator.get_sort_key(a.title)] <=> [b.casting, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_casting_and_title_desc, lambda {
    sort do |a, b|
      [b.casting, Spell.collator.get_sort_key(a.title)] <=> [a.casting, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_range_and_title_asc, lambda {
    sort do |a, b|
      [a.range, Spell.collator.get_sort_key(a.title)] <=> [b.range, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_range_and_title_desc, lambda {
    sort do |a, b|
      [b.range, Spell.collator.get_sort_key(a.title)] <=> [a.range, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_duration_and_title_asc, lambda {
    sort do |a, b|
      [a.duration, Spell.collator.get_sort_key(a.title)] <=> [b.duration, Spell.collator.get_sort_key(b.title)]
    end
  }
  scope :sort_by_duration_and_title_desc, lambda {
    sort do |a, b|
      [b.duration, Spell.collator.get_sort_key(a.title)] <=> [a.duration, Spell.collator.get_sort_key(b.title)]
    end
  }

  CASTING = {
    '1 reakce' => 0, '1 bonusová akce' => 1, '1 akce' => 2, '1 akce, nebo 8 hodin' => 3,
    '1 minuta' => 4, '10 minut' => 5, '1 hodina' => 6, '8 hodin' => 7, '12 hodin' => 8,
    '24 hodin' => 9
  }.freeze

  RANGE = {
    'Ty sám' => 0, 'Ty sám (oblast)' => 1, 'Dotyk' => 2, '1 sáh' => 3, '2 sáhy' => 4,
    '3 sáhy' => 5, '6 sáhů' => 6, '6 sáhů (oblast)' => 7, '9 sáhů (oblast)' => 8,
    '10 sáhů' => 9, '12 sáhů' => 10, '15 sáhů' => 11, '16 sáhů' => 12, '18 sáhů' => 13,
    '20 sáhů' => 14, '24 sáhů' => 15, '30 sáhů' => 16, '60 sáhů' => 17, '100 sáhů' => 18,
    'Dohled' => 19, '1 míle' => 20, '800 mil' => 21, 'Neomezený' => 22, 'Zvláštní' => 23
  }.freeze

  DURATION = {
    'Ihned' => 0, 'Ihned, nebo 1 hodina' => 1, '1 kolo' => 2, '5 kol' => 3, '6 kol' => 4, '1 minuta' => 5,
    '10 minut' => 6, '1 hodina' => 7, '2 hodiny' => 8, '8 hodin' => 9, '24 hodin' => 10,
    '1 den' => 11, '7 dní' => 12, '10 dní' => 13, '30 dní' => 14, 'Do rozptýlení' => 15,
    'Do rozptýlení, nebo spuštění' => 16, 'Zvláštní' => 17
  }.freeze
end

app/controllers/dnd_controller.rb
class DndController < ApplicationController
  def kouzla
    @q = Spell.ransack(present_params)
    @elements = @q.result
  end

  def predmety
    @q = Dnd::Item.ransack(present_params)
    @elements = @q.result
  end

  private

  def present_params
    params[:q]&.reject { |_k, v| v == '0' }
  end
end

app/helpers/dnd_helper.rb
module DndHelper
  def dnd_spell_description(spell)
    description = "# #{spell.title}"
    description += "\n*#{spell.original}*" if spell.original
    description += "\n\n***#{spell.rulebook.join(', ')}***\n"
    description += "\n\n*#{spell.school} #{spell.level}. úrovně#{' (rituál)' if spell.ritual}*"
    description += "\n\n**Vyvolání:** #{spell.original_casting}"
    description += "\n\n**Dosah:** #{spell.original_range}"
    description += "\n\n**Složky:** #{spell.original_components}"
    description += "\n\n**Trvání:** #{spell.original_duration}#{spell.concentration ? ' (soustředění)' : ''}"
    description += "\n\n**Povolání:** #{spell.classes.join(', ')}"
    description += "\n\n#{spell.description}"
    description
  end

  def dnd_item_description(item)
    description = "# #{item.title}"
    description += "\n*#{item.original}*" if item.original
    description += "\n\n***#{item.rulebook.join(', ')}***\n"
    description += "\n\n#{item.description}"
    description
  end
end

app/views/dnd/spells/_filters.html.slim
.text-dark
  .form-background.p-3.mt-3.delimiter
    = search_form_for @q, url: kouzla_dnd_index_path do |f|
      .row
        .col-md-5.col-lg-3
          = f.input :title_cont, required: false, placeholder: 'Český', label: 'Název'
          = f.input :original_cont, required: false, placeholder: 'Anglický', label: false
        .col-md-7.col-lg-4 = f.input :rulebook_array_overlaps, required: false, label: 'Zdroj', collection: psql_array_czech_sort(Spell.pluck(:rulebook)), include_blank: true, input_html: { multiple: true }
        .col-5.col-md-3.col-lg-2 = f.input :school_in, required: false, label: 'Škola', collection: collator.sort(Spell.pluck(:school).uniq), include_blank: true, input_html: { multiple: true }
        .col-3.col-md-2.col-lg-1 = f.input :level_in, required: false, label: 'Stupeň', collection: Spell.pluck(:level).uniq.sort, include_blank: true, input_html: { multiple: true }
        .col-6.col-md-3.col-lg-2 = f.input :range_in, required: false, label: 'Dosah', collection: Spell::RANGE, include_blank: true, input_html: { multiple: true }
        .col-8.col-md-4.col-lg-3 = f.input :casting_in, required: false, label: 'Vyvolání', collection: Spell::CASTING, include_blank: true, input_html: { multiple: true }
        .col-3.col-md-2.col-lg-1
          fieldset.mb-3.check_boxes.optional.q_ritual_eq
            legend.col-form-label.heading-font.pt-0 Rituál?
            .form-check
              = f.check_box :ritual_true, required: false, label: 'Ano', class: 'form-check-input check_boxes optional'
              = f.label :ritual_true, 'Ano', class: 'form-check-label'
            .form-check
              = f.check_box :ritual_false, required: false, label: 'Ne', class: 'form-check-input check_boxes optional'
              = f.label :ritual_false, 'Ne', class: 'form-check-label'
        .col-4.col-md-3.col-lg-2 = f.input :components_in, required: false, label: 'Složky', collection: Spell.pluck(:components).uniq.sort, include_blank: true, input_html: { multiple: true }
        .col-6.col-md-3.col-lg-2 = f.input :classes_array_overlaps, required: false, label: 'Povolání', collection: psql_array_czech_sort(Spell.pluck(:classes)), include_blank: true, input_html: { multiple: true }
        .col-10.col-md-5.col-lg-3 = f.input :duration_in, required: false, label: 'Trvání', collection: Spell::DURATION, include_blank: true, input_html: { multiple: true }
        .col-3.col-md-2.col-lg-1
          fieldset.mb-3.check_boxes.optional.q_concentration_eq
            legend.col-form-label.heading-font.pt-0 Soustředění?
            .form-check
              = f.check_box :concentration_true, required: false, label: 'Ano', class: 'form-check-input check_boxes optional'
              = f.label :concentration_true, 'Ano', class: 'form-check-label'
            .form-check
              = f.check_box :concentration_false, required: false, label: 'Ne', class: 'form-check-input check_boxes optional'
              = f.label :concentration_false, 'Ne', class: 'form-check-label'
      = render 'shared/form/footer', elements: 'kouzel', f: f, link: kouzla_dnd_index_path

  .form-background.mb-5.p-3
    h5 Seřadit podle
    .mb-1
      = sort_link(@q, :czech_title, 'Názvu', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :school_and_title, 'Školy', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :level_and_title, 'Stupně', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :casting_and_title, 'Vyvolání', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :range_and_title, 'Dosahu', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :duration_and_title, 'Trvání', {}, class: 'btn btn-secondary m-1')

app/views/dnd/spells/_spell.html.slim
.accordion-item
  h2.accordion-header id="spellPanels-heading#{spell.id}"
    .accordion-button.collapsed type="button" data-bs-toggle="collapse" data-bs-target="#spellPanels-collapse#{spell.id}" aria-expanded="true" aria-controls="spellPanels-collapse#{spell.id}"
      .container
        .row
          .col-md-5.col-lg-3.fw-bold = spell.title
          .col-md-2.col-lg-1 Stupeň: #{spell.level}.
          .col-md-4.col-lg-2 Škola: #{spell.school}
          .col-md-4.col-lg-2 Vyvolání: #{Spell::CASTING.key(spell.casting)}
          .col-md-4.col-lg-2 Dosah: #{Spell::RANGE.key(spell.range)}
          .col-md-4.col-lg-2 Trvání: #{Spell::DURATION.key(spell.duration)}#{spell.concentration ? ' (s.)' : ''}
  .accordion-collapse.collapse id="spellPanels-collapse#{spell.id}" aria-labelledby="spellPanels-heading#{spell.id}"
    .accordion-body
      = CommonMarker.render_html(dnd_spell_description(spell), :HARDBREAKS).html_safe