config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dnd, only: [] do
    collection do
      get :kouzla
      get :predmety
    end
  end

  resources :fate, only: [] do
    collection do
      get :triky
    end
  end

  resources :drd2, only: [] do
    collection do
      get :schopnosti
    end
  end
end

app/models/dnd.rb
module Dnd
  def self.table_name_prefix
    'dnd_'
  end
end

app/models/dnd/class_spell.rb
# == Schema Information
#
# Table name: class_spells
#
#  id           :bigint           not null, primary key
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  dnd_class_id :bigint           not null
#  spell_id     :bigint           not null
#
# Indexes
#
#  index_class_spells_on_dnd_class_id  (dnd_class_id)
#  index_class_spells_on_spell_id      (spell_id)
#
# Foreign Keys
#
#  fk_rails_...  (dnd_class_id => dnd_classes.id)
#  fk_rails_...  (spell_id => spells.id)
#
module Dnd
  class ClassSpell < ApplicationRecord
    belongs_to :spell
    belongs_to :dnd_class
  end
end

app/models/dnd/dnd_class.rb
# == Schema Information
#
# Table name: dnd_classes
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Dnd
  class DndClass < ApplicationRecord
    has_many :class_spells
    has_many :spells, through: :class_spells

    validates :name, presence: true, uniqueness: true
  end
end

app/models/dnd/item.rb
# == Schema Information
#
# Table name: dnd_items
#
#  id              :bigint           not null, primary key
#  attunement      :string           default([]), is an Array
#  bonus           :string           default([]), is an Array
#  combat_effect   :string           default([]), is an Array
#  description     :text
#  duration        :string
#  filter_duration :integer
#  filter_rarity   :integer          default([]), is an Array
#  interaction     :string
#  item            :string           default([]), is an Array
#  limit           :string           default([]), is an Array
#  original        :string
#  purpose         :string           default([]), is an Array
#  rarity          :string
#  rulebook        :string           default([]), is an Array
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
module Dnd
  class Item < ApplicationRecord
    scope :sort_by_czech_title_asc, -> { sort { |a, b| Dnd::Item.collator.compare(a.title, b.title) } }
    scope :sort_by_czech_title_desc, -> { sort { |a, b| Dnd::Item.collator.compare(b.title, a.title) } }
    scope :sort_by_item_and_title_asc, lambda {
      sort do |a, b|
        [Dnd::Item.collator.get_sort_key(a.item.first), Dnd::Item.collator.get_sort_key(a.title)] <=>
          [Dnd::Item.collator.get_sort_key(b.item.first), Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_item_and_title_desc, lambda {
      sort do |a, b|
        [Dnd::Item.collator.get_sort_key(b.item.first), Dnd::Item.collator.get_sort_key(a.title)] <=>
          [Dnd::Item.collator.get_sort_key(a.item.first), Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_rarity_and_title_asc, lambda {
      sort do |a, b|
        [a.filter_rarity.first, Dnd::Item.collator.get_sort_key(a.title)] <=>
          [b.filter_rarity.first, Dnd::Item.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_rarity_and_title_desc, lambda {
      sort do |a, b|
        [b.filter_rarity.first, Dnd::Item.collator.get_sort_key(a.title)] <=>
          [a.filter_rarity.first, Dnd::Item.collator.get_sort_key(b.title)]
      end
    }

    DURATION = {
      'Ihned' => 0,
      '1 kolo' => 1,
      'X kol' => 2,
      '1 minuta' => 3,
      '5 minut' => 4,
      '10 minut' => 5,
      'X minut' => 6,
      '1 hodina' => 7,
      '2 hodiny' => 8,
      '4 hodiny' => 9,
      '6 hodin' => 10,
      '8 hodin' => 11,
      'X hodin' => 12,
      'X dní' => 13,
      'Do rozptýlení' => 14,
      'Permanentní' => 15,
      'Zvláštní' => 16,
      'nepovinný' => 17
    }.freeze

    RARITY = {
      'Běžný' => 0,
      'Neobvyklý' => 1,
      'Vzácný' => 2,
      'Velmi vzácný' => 3,
      'Legendární' => 4,
      'Artefakt' => 5
    }.freeze
  end
end

app/models/dnd/rulebook.rb
# == Schema Information
#
# Table name: rulebooks
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module Dnd
  class Rulebook < ApplicationRecord
    has_many :sources
    has_many :spells, through: :sources
  end
end

app/models/dnd/source.rb
# == Schema Information
#
# Table name: sources
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  rulebook_id :bigint           not null
#  spell_id    :bigint           not null
#
# Indexes
#
#  index_sources_on_rulebook_id  (rulebook_id)
#  index_sources_on_spell_id     (spell_id)
#
# Foreign Keys
#
#  fk_rails_...  (rulebook_id => rulebooks.id)
#  fk_rails_...  (spell_id => spells.id)
#
module Dnd
  class Source < ApplicationRecord
    belongs_to :spell
    belongs_to :rulebook
  end
end

app/controllers/dnd_controller.rb
class DndController < ApplicationController
  def kouzla
    @q = Spell.ransack(present_params)
    @elements = @q.result
  end

  def predmety
    @q = Dnd::Item.ransack(present_params)
    @elements = @q.result
  end

  private

  def present_params
    params[:q]&.reject { |_k, v| v == '0' }
  end
end

app/helpers/dnd_helper.rb
module DndHelper
  def dnd_spell_description(spell)
    description = "# #{spell.title}"
    description += "\n*#{spell.original}*" if spell.original
    description += "\n\n***#{spell.rulebook.join(', ')}***\n"
    description += "\n\n*#{spell.school} #{spell.level}. úrovně#{' (rituál)' if spell.ritual}*"
    description += "\n\n**Vyvolání:** #{spell.original_casting}"
    description += "\n\n**Dosah:** #{spell.original_range}"
    description += "\n\n**Složky:** #{spell.original_components}"
    description += "\n\n**Trvání:** #{spell.original_duration}#{spell.concentration ? ' (soustředění)' : ''}"
    description += "\n\n**Povolání:** #{spell.classes.join(', ')}"
    description += "\n\n#{spell.description}"
    description
  end

  def dnd_item_description(item)
    description = "# #{item.title}"
    description += "\n*#{item.original}*" if item.original
    description += "\n\n***#{item.rulebook.join(', ')}***\n"
    description += "\n\n#{item.description}"
    description
  end
end

app/views/dnd/items/_filters.html.slim
.text-dark
  .form-background.p-3.mt-3.delimiter
    = search_form_for @q, url: predmety_dnd_index_path do |f|
      .row
        .col-md-5.col-lg-3
          = f.input :title_cont, required: false, placeholder: 'Český', label: 'Název'
          = f.input :original_cont, required: false, placeholder: 'Anglický', label: false
        .col-8.col-md-5.col-lg-3 = f.input :rulebook_array_overlaps, required: false, label: 'Zdroj', collection: psql_array_czech_sort(Dnd::Item.pluck(:rulebook)), include_blank: true, input_html: { multiple: true }
        .col-6.col-md-4.col-lg-2 = f.input :item_array_overlaps, required: false, label: 'Předmět', collection: psql_array_czech_sort(Dnd::Item.pluck(:item)), include_blank: true, input_html: { multiple: true }
        .col-6.col-md-3.col-lg-2 = f.input :filter_rarity_array_overlaps, required: false, label: 'Vzácnost', collection: Dnd::Item::RARITY, include_blank: true, input_html: { multiple: true }
        .col-5.col-md-3.col-lg-2 = f.input :interaction_in, required: false, label: 'Interakce', collection: Dnd::Item.pluck(:interaction).uniq.sort, include_blank: true, input_html: { multiple: true }

        .col-6.col-md-3.col-lg-2 = f.input :bonus_array_overlaps, required: false, label: 'Bonus', collection: psql_array_czech_sort(Dnd::Item.pluck(:bonus)), include_blank: true, input_html: { multiple: true }
        .col-6.col-md-4.col-lg-2 = f.input :combat_effect_array_overlaps, required: false, label: 'Bojový efekt', collection: psql_array_czech_sort(Dnd::Item.pluck(:combat_effect)), include_blank: true, input_html: { multiple: true }
        .col-6.col-md-4.col-lg-2 = f.input :limit_array_overlaps, required: false, label: 'Limit', collection: psql_array_czech_sort(Dnd::Item.pluck(:limit)), include_blank: true, input_html: { multiple: true }
        .col-5.col-md-3.col-lg-2 = f.input :filter_duration_in, required: false, label: 'Trvání', collection: Dnd::Item::DURATION, include_blank: true, input_html: { multiple: true }
        .col-6.col-md-4.col-lg-2 = f.input :attunement_array_overlaps, required: false, label: 'Sladění', collection: psql_array_czech_sort(Dnd::Item.pluck(:attunement)), include_blank: true, input_html: { multiple: true }
        .col-6.col-md-4.col-lg-2 = f.input :purpose_array_overlaps, required: false, label: 'Účel', collection: psql_array_czech_sort(Dnd::Item.pluck(:purpose)), include_blank: true, input_html: { multiple: true }

      = render 'shared/form/footer', elements: 'předmětů', f: f, link: predmety_dnd_index_path

  .form-background.mb-5.p-3
    h5 Seřadit podle
    .mb-1
      = sort_link(@q, :czech_title, 'Názvu', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :item_and_title, 'Předmětu', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :rarity_and_title, 'Vzácnosti', {}, class: 'btn btn-secondary m-1')

app/views/dnd/items/_item.html.slim
.accordion-item
  h2.accordion-header id="itemPanels-heading#{item.id}"
    .accordion-button.collapsed type="button" data-bs-toggle="collapse" data-bs-target="#itemPanels-collapse#{item.id}" aria-expanded="true" aria-controls="itemPanels-collapse#{item.id}"
      .container
        .row
          .col-md-5.col-lg-3.fw-bold = item.title
          .col-md-4.col-lg-2 #{item.item.join(', ')}
          .col-md-8.col-lg-4 #{item.rarity}
  .accordion-collapse.collapse id="itemPanels-collapse#{item.id}" aria-labelledby="itemPanels-heading#{item.id}"
    .accordion-body
      = CommonMarker.render_html(dnd_item_description(item), :HARDBREAKS).html_safe