config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dnd, only: [] do
    collection do
      get :kouzla
      get :predmety
    end
  end

  resources :fate, only: [] do
    collection do
      get :triky
    end
  end

  resources :drd2, only: [] do
    collection do
      get :schopnosti
    end
  end
end

app/views/pages/_fate_filters.html.slim
.form-background.p-3.mt-3.delimiter
  = search_form_for @q, url: fate_path do |f|
    .row
      .col-md-5.col-lg-3
        = f.input :title_cont, required: false, placeholder: 'Český', label: 'Název'
        = f.input :original_cont, required: false, placeholder: 'Anglický', label: false
      .col-8.col-md-4.col-lg-3 = f.input :source_in, required: false, label: 'Zdroj', collection: Fate::Trick.pluck(:source).uniq.sort, include_blank: true, input_html: { multiple: true }
      / .col-5.col-md-3.col-lg-2 = f.input :origin_in, required: false, label: 'Původ', collection: Fate::Trick.pluck(:origin).uniq.compact.sort, include_blank: true, input_html: { multiple: true }

      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FAE přístupy', collection: psql_array_czech_sort(Fate::Trick.pluck(:fae_approach)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FC speciality', collection: psql_array_czech_sort(Fate::Trick.pluck(:fc_extra)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FC dovednosti', collection: psql_array_czech_sort(Fate::Trick.pluck(:fc_skill)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW archetypy', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_archetype)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW protivníci', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_enemy)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW speciality', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_extra)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW rasy', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_race)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }
      .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW dovednosti', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_skill)), include_blank: true, input_html: { multiple: true, class: 'shared-selection' }

      .col-6.col-md-3.col-lg-2 = f.input :tags_array_overlaps, required: false, label: 'Tag', collection: psql_array_czech_sort(Fate::Trick.pluck(:tags)), include_blank: true, input_html: { multiple: true }
      .col-4.col-md-2.col-lg-2 = f.input :trick_type_array_overlaps, required: false, label: 'Typ', collection: psql_array_czech_sort(Fate::Trick.pluck(:trick_type)), include_blank: true, input_html: { multiple: true }
      .col-3.col-md-2.col-lg-1 = f.input :actions_array_overlaps, required: false, label: 'Akce', collection: psql_array_czech_sort(Fate::Trick.pluck(:actions)), include_blank: true, input_html: { multiple: true }
      .col-4.col-md-2.col-lg-2 = f.input :restrictions_array_overlaps, required: false, label: 'Omezení', collection: psql_array_czech_sort(Fate::Trick.pluck(:restrictions)), include_blank: true, input_html: { multiple: true }
      .col-4.col-md-2.col-lg-2 = f.input :costs_array_overlaps, required: false, label: 'Cena', collection: psql_array_czech_sort(Fate::Trick.pluck(:costs)), include_blank: true, input_html: { multiple: true }
    p.text-muted Pro výběr více možností v jedné kategorii držte tlačítko CTRL. Mapování triků je mechanické - při použití triku z jiného zdroje vždy zvaž stylizaci!
    .d-flex.justify-content-between
      p
        span.text-primary.me-1 = @tricks.size
        | triků nalezeno
      div
        = link_to 'Reset', fate_path, class: 'btn btn-outline-secondary mx-0 mx-sm-3'
        = f.submit 'Hledat', class: 'btn btn-primary'

.form-background.mb-5.p-3
  h5 Seřadit podle
  .mb-1
    = sort_link(@q, :czech_title, 'Názvu', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :dial_and_title, 'Dovednosti', {}, class: 'btn btn-secondary m-1')

app/views/pages/_filters.html.slim
.form-background.p-3.mt-3.delimiter
  = search_form_for @q, url: dnd_path do |f|
    .row
      .col-md-5.col-lg-3
        = f.input :name_cont, required: false, placeholder: 'Český', label: 'Název'
        = f.input :en_name_cont, required: false, placeholder: 'Anglický', label: false
      .col-md-7.col-lg-4 = f.input :rulebook_in, required: false, label: 'Zdroj', collection: Spell.pluck(:rulebook).uniq.sort, include_blank: true, input_html: { multiple: true }
      .col-5.col-md-3.col-lg-2 = f.input :school_in, required: false, label: 'Škola', collection: collator.sort(Spell.pluck(:school).uniq), include_blank: true, input_html: { multiple: true }
      .col-3.col-md-2.col-lg-1 = f.input :level_in, required: false, label: 'Stupeň', collection: Spell.pluck(:level).uniq.sort, include_blank: true, input_html: { multiple: true }
      .col-6.col-md-3.col-lg-2 = f.input :range_in, required: false, label: 'Dosah', collection: Spell::RANGE, include_blank: true, input_html: { multiple: true }
      .col-8.col-md-4.col-lg-3 = f.input :casting_in, required: false, label: 'Vyvolání', collection: Spell::CASTING, include_blank: true, input_html: { multiple: true }
      .col-3.col-md-2.col-lg-1 = f.input :ritual_eq, required: false, label: 'Rituál?', collection: [['Ano', true], ['Ne', false]], as: :check_boxes, boolean_style: :nested
      .col-4.col-md-2.col-lg-2 = f.input :components_in, required: false, label: 'Složky', collection: Spell.pluck(:components).uniq.sort, include_blank: true, input_html: { multiple: true }
      .col-6.col-md-3.col-lg-2 = f.input :classes_array_overlaps, required: false, label: 'Povolání', collection: psql_array_czech_sort(Spell.pluck(:classes)), include_blank: true, input_html: { multiple: true }
      .col-9.col-md-5.col-lg-3 = f.input :duration_in, required: false, label: 'Trvání', collection: Spell::DURATION, include_blank: true, input_html: { multiple: true }
      .col-3.col-md-2.col-lg-1 = f.input :concentration_eq, required: false, label: 'Soustředění?', collection: [['Ano', true], ['Ne', false]], as: :check_boxes, boolean_style: :nested
    p.text-muted Pro výběr více možností v jedné kategorii držte tlačítko CTRL.
    .d-flex.justify-content-between
      p
        span.text-primary.me-1 = @spells.size
        | kouzel nalezeno
      div
        = link_to 'Reset', dnd_path, class: 'btn btn-outline-secondary mx-0 mx-sm-3'
        = f.submit 'Hledat', class: 'btn btn-primary'

.form-background.mb-5.p-3
  h5 Seřadit podle
  .mb-1
    = sort_link(@q, :czech_name, 'Názvu', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :school_and_name, 'Školy', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :level_and_name, 'Stupně', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :casting_and_name, 'Vyvolání', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :range_and_name, 'Dosahu', {}, class: 'btn btn-secondary m-1')
    = sort_link(@q, :duration_and_name, 'Trvání', {}, class: 'btn btn-secondary m-1')

app/views/pages/dnd.html.slim
- content_for :title, 'DnD 5e kartotéka kouzel'

h1.mt-5 DnD 5e kartotéka kouzel
.d-flex.justify-content-between
  p.card-subtitle.text-muted powered by #{link_to 'd20.cz', 'http://www.d20.cz', target: :blank, class: 'text-muted'}
  = link_to 'Zpátky k rozcestníku', root_path, class: 'card-subtitle text-muted'
= render 'filters'

.accordion.custom-accordion
  = render partial: 'spell', collection: @spells

app/views/pages/fate.html.slim
- content_for :title, 'Fate kartotéka triků'

h1.mt-5 Fate kartotéka triků
.d-flex.justify-content-between
  p.card-subtitle.text-muted powered by #{link_to 'd20.cz', 'http://www.d20.cz', target: :blank, class: 'text-muted'}
  = link_to 'Zpátky k rozcestníku', root_path, class: 'card-subtitle text-muted'
= render 'fate_filters'

.accordion.custom-accordion
  = render partial: 'fate_trick', collection: @tricks

app/views/pages/home.html.slim
h1.mt-5 SRD kartotéky
= render 'shared/form/subtitle'

.row.mt-5.justify-content-center
  - @cards.each do |path, v|
    .col-md-6.col-lg-3.my-1
      .form-background.card.link_card.p-3.text-center
        .d-flex.align-items-center style="height: 140px;"
          = image_tag v[:img], class: 'card-img-top'
        h5.card-link = link_to "#{icon('fa-solid', v[:icon]) if v[:icon]}#{v[:text]}".html_safe, path, class: "stretched-link text-#{cookies[:theme] == 'light' ? 'primary' : 'danger'}"