config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dnd, only: [] do
    collection do
      get :kouzla
      get :predmety
    end
  end

  resources :fate, only: [] do
    collection do
      get :triky
    end
  end

  resources :drd2, only: [] do
    collection do
      get :schopnosti
    end
  end
end

app/models/fate.rb
module Fate
  def self.table_name_prefix
    'fate_'
  end
end

app/models/fate/trick.rb
# == Schema Information
#
# Table name: fate_tricks
#
#  id           :bigint           not null, primary key
#  actions      :string           default([]), is an Array
#  costs        :string           default([]), is an Array
#  description  :text
#  dials        :string           default([]), is an Array
#  fae_approach :string           default([]), is an Array
#  fc_extra     :string           default([]), is an Array
#  fc_skill     :string           default([]), is an Array
#  origin       :string
#  original     :string
#  restrictions :string           default([]), is an Array
#  source       :string
#  sw_archetype :string           default([]), is an Array
#  sw_enemy     :string           default([]), is an Array
#  sw_extra     :string           default([]), is an Array
#  sw_race      :string           default([]), is an Array
#  sw_skill     :string           default([]), is an Array
#  tags         :string           default([]), is an Array
#  title        :string
#  trick_type   :string           default([]), is an Array
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
module Fate
  class Trick < ApplicationRecord
    scope :sort_by_czech_title_asc, -> { sort { |a, b| Fate::Trick.collator.compare(a.title, b.title) } }
    scope :sort_by_czech_title_desc, -> { sort { |a, b| Fate::Trick.collator.compare(b.title, a.title) } }
    scope :sort_by_dial_and_title_asc, lambda {
      sort do |a, b|
        [Fate::Trick.collator.get_sort_key(a.dials.first), Fate::Trick.collator.get_sort_key(a.title)] <=>
          [Fate::Trick.collator.get_sort_key(b.dials.first), Fate::Trick.collator.get_sort_key(b.title)]
      end
    }
    scope :sort_by_dial_and_title_desc, lambda {
      sort do |a, b|
        [Fate::Trick.collator.get_sort_key(b.dials.first), Fate::Trick.collator.get_sort_key(a.title)] <=>
          [Fate::Trick.collator.get_sort_key(a.dials.first), Fate::Trick.collator.get_sort_key(b.title)]
      end
    }

    STRING_COLUMNS = %i[origin original source title].freeze
  end
end

app/controllers/fate_controller.rb
class FateController < ApplicationController
  def triky
    @q = Fate::Trick.ransack(params[:q])
    @elements = @q.result
  end
end

app/helpers/fate_helper.rb
module FateHelper
  def fate_trick_description(trick)
    description = "# #{trick.title}"
    description += "\n*#{trick.original}*" if trick.original
    description += "\n\n***#{trick.source}***\n"
    description += "\n\n**FAE přístup:** #{trick.fae_approach.join(', ')}" unless trick.fae_approach.blank?
    description += "\n\n**FC specialita:** #{trick.fc_extra.join(', ')}" unless trick.fc_extra.blank?
    description += "\n\n**FC dovednost:** #{trick.fc_skill.join(', ')}" unless trick.fc_skill.blank?
    description += "\n\n**SW archetyp:** #{trick.sw_archetype.join(', ')}" unless trick.sw_archetype.blank?
    description += "\n\n**SW protivník:** #{trick.sw_enemy.join(', ')}" unless trick.sw_enemy.blank?
    description += "\n\n**SW specialita:** #{trick.sw_extra.join(', ')}" unless trick.sw_extra.blank?
    description += "\n\n**SW rasa:** #{trick.sw_race.join(', ')}" unless trick.sw_race.blank?
    description += "\n\n**SW dovednost:** #{trick.sw_skill.join(', ')}" unless trick.sw_skill.blank?
    description += "\n\n**Tagy:** #{trick.tags.join(', ')}" unless trick.tags.blank?
    description += "\n\n**Typ:** #{trick.trick_type.join(', ')}" unless trick.trick_type.blank?
    description += "\n\n**Akce:** #{trick.actions.join(', ')}" unless trick.actions.blank?
    description += "\n\n**Omezení:** #{trick.restrictions.join(', ')}" unless trick.restrictions.blank?
    description += "\n\n**Cena:** #{trick.costs.join(', ')}" unless trick.costs.blank?
    description += "\n\n#{trick.description}"
    description
  end
end

app/views/fate/_fate_filters.html.slim
.text-dark
  .form-background.p-3.mt-3.delimiter
    = search_form_for @q, url: triky_fate_index_path do |f|
      .row
        .col-md-5.col-lg-3
          = f.input :title_cont, required: false, placeholder: 'Český', label: 'Název'
          = f.input :original_cont, required: false, placeholder: 'Anglický', label: false
        .col-8.col-md-4.col-lg-3 = f.input :source_in, required: false, label: 'Zdroj', collection: Fate::Trick.pluck(:source).uniq.sort.reverse, include_blank: true, input_html: { multiple: true }
        / .col-5.col-md-3.col-lg-2 = f.input :origin_in, required: false, label: 'Původ', collection: Fate::Trick.pluck(:origin).uniq.compact.sort, include_blank: true, input_html: { multiple: true }

        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FAE přístupy', collection: psql_array_czech_sort(Fate::Trick.pluck(:fae_approach)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FC speciality', collection: psql_array_czech_sort(Fate::Trick.pluck(:fc_extra)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'FC dovednosti', collection: psql_array_czech_sort(Fate::Trick.pluck(:fc_skill)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW archetypy', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_archetype)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW protivníci', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_enemy)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW speciality', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_extra)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW rasy', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_race)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }
        .col-5.col-md-3.col-lg-2 = f.input :dials_array_overlaps, required: false, label: 'SW dovednosti', collection: psql_array_czech_sort(Fate::Trick.pluck(:sw_skill)), include_blank: true, input_html: { multiple: true, class: "text-bg-#{cookies[:theme]}" }

        .col-6.col-md-3.col-lg-2 = f.input :tags_array_overlaps, required: false, label: 'Tag', collection: psql_array_czech_sort(Fate::Trick.pluck(:tags)), include_blank: true, input_html: { multiple: true }
        .col-4.col-md-2.col-lg-2 = f.input :trick_type_array_overlaps, required: false, label: 'Typ', collection: psql_array_czech_sort(Fate::Trick.pluck(:trick_type)), include_blank: true, input_html: { multiple: true }
        .col-3.col-md-2.col-lg-1 = f.input :actions_array_overlaps, required: false, label: 'Akce', collection: %w[O CA A D AO], include_blank: true, input_html: { multiple: true }
        .col-4.col-md-2.col-lg-2 = f.input :restrictions_array_overlaps, required: false, label: 'Omezení', collection: psql_array_czech_sort(Fate::Trick.pluck(:restrictions)), include_blank: true, input_html: { multiple: true }
        .col-4.col-md-2.col-lg-2 = f.input :costs_array_overlaps, required: false, label: 'Cena', collection: psql_array_czech_sort(Fate::Trick.pluck(:costs)), include_blank: true, input_html: { multiple: true }

      - @extra_instructions = 'Mapování triků je mechanické - při použití triku z jiného zdroje vždy zvaž stylizaci!'
      = render 'shared/form/footer', elements: 'triků', f: f, link: triky_fate_index_path

  .form-background.mb-5.p-3
    h5 Seřadit podle
    .mb-1
      = sort_link(@q, :czech_title, 'Názvu', {}, class: 'btn btn-secondary m-1')
      = sort_link(@q, :dial_and_title, 'Dovednosti', {}, class: 'btn btn-secondary m-1')

app/views/fate/_fate_trick.html.slim
.accordion-item
  h2.accordion-header id="fate_trickPanels-heading#{fate_trick.id}"
    .accordion-button.collapsed type="button" data-bs-toggle="collapse" data-bs-target="#fate_trickPanels-collapse#{fate_trick.id}" aria-expanded="true" aria-controls="fate_trickPanels-collapse#{fate_trick.id}"
      .container
        .row
          .col-md-5.col-lg-3.fw-bold = fate_trick.title
          .col-md-5.col-lg-3 = fate_trick.dials.join(', ')
          .col-md-2.col-lg-1 = fate_trick.actions.join(', ')
          .col-md-5.col-lg-3 = fate_trick.trick_type.join(', ')
          .col-md-4.col-lg-2 = fate_trick.restrictions.join(', ')
  .accordion-collapse.collapse id="fate_trickPanels-collapse#{fate_trick.id}" aria-labelledby="fate_trickPanels-heading#{fate_trick.id}"
    .accordion-body
      = CommonMarker.render_html(fate_trick_description(fate_trick), :HARDBREAKS).html_safe

app/views/fate/triky.html.slim
- content_for :title, 'Fate kartotéka triků'
- content_for :meta_title, 'Fate kartotéka triků'

h1.mt-5 Fate kartotéka triků
= render 'shared/form/subtitle'
= render 'fate_filters'

.accordion.custom-accordion
  = render partial: 'fate_trick', collection: @elements